/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Usuarios;
import Logica.DatosUsuario; 
import java.awt.Color;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ana
 */
public class FormUsuarios extends javax.swing.JInternalFrame {   
    
    //Creamos variables
    private DefaultTableModel modelo;
    private String acc = "guardar";
    private DatosUsuario usu;
    private Usuarios usuario;
   
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public FormUsuarios() {
        initComponents();
        //Color JFrame en blanco
        this.getContentPane().setBackground(Color.white); 
//        this.fillTable(""); //Mostrar los valores de la tabla
        MostrarDatosTabla(""); //Mostrar los valores de la tabla
        inhabilitar();
    }
 
//    //Para ocultar los campos id de las trablas
//    void ocultar_columnas(){
//       tablausu.getColumnModel().getColumn(0).setMaxWidth(0);
//       tablausu.getColumnModel().getColumn(0).setMinWidth(0);
//       tablausu.getColumnModel().getColumn(0).setPreferredWidth(0);       
//    }
    
    //Inhabilitar los valores de las cajas
    private void inhabilitar (){
        txtidusuarios.setEnabled(false);
        txtnombre.setEnabled(false);
        txtapellidos.setEnabled(false);
        txtemail.setEnabled(false);
        txtpassword.setEnabled(false);
        txtpassword2.setEnabled(false);
        cbmperfil.setEnabled(false);
        
        btnguardar.setEnabled(false);
        btncancelar.setEnabled(false);
        btnborrar.setEnabled(false);
        //Limpiar campos
        limpiar(); 
    }
    //Habilitar los valores de las cajas
    private void habilitar (){
        txtidusuarios.setEnabled(true);
        txtnombre.setEnabled(true);
        txtapellidos.setEnabled(true);
        txtemail.setEnabled(true);
        txtpassword.setEnabled(true);
        txtpassword2.setEnabled(true);
        cbmperfil.setEnabled(true);
        
        btnguardar.setEnabled(true);
        btncancelar.setEnabled(true);
        btnborrar.setEnabled(true);
        
        limpiar();
    }
    //Limpiar Campos
    private void limpiar(){        
        txtidusuarios.setText("");
        txtnombre.setText("");
        txtapellidos.setText("");
        txtemail.setText("");
        txtpassword.setText(""); 
        txtpassword2.setText("");
        cbmperfil.setSelectedIndex(0);
    } 
    //LLenar tabla con ArrayList - Metodo dos
//    private void fillTable(String buscar) {
//        try {
//            usu = new DatosUsuario();
//            ArrayList<Usuarios> user = usu.getAllUsuarios(buscar);
//            String columnas[] = {"Usuarios", "Nombre", "Apellidos", "Email", "Password", "Password2", "Perfil"};
//            this.modelo = new DefaultTableModel(columnas, 0);
//            this.tablausu.setModel(modelo);
//            
//            for (Usuarios users : user){
//               Object[] row = {
//                   users.getIdusuarios(),
//                   users.getNombre(),
//                   users.getApellidos(),
//                   users.getEmail(),
//                   users.getPassword(),
//                   users.getPassword(),
//                   users.getPerfil()
//               };
//               this.modelo.addRow(row);
//            }
//            
//            lbltotalregistros.setText("Total Registros  " + Integer.toString(usu.totalRegistros));
//        } catch (Exception e) {
//            JOptionPane.showConfirmDialog(null, e);
//        }
//    }
//    
    //Metodo buscar tabla con modelo - Metodo uno
    private void MostrarDatosTabla(String buscar){
        try { 
             usu = new DatosUsuario();
             //Al modelo la tabla usuario y le pasamos el usuario a buscar
             modelo = usu.UsuTable(buscar); 
             //Añadimos a la tabla el modelo
             tablausu.setModel(modelo);
             //Indicamos el total de registros obtenidos
             lbltotalregistros.setText("Total Registros -----    " + Integer.toString(usu.totalRegistros)); 
             
        } catch (Exception e) {
             JOptionPane.showConfirmDialog(null,e);
        }
     } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblperfil = new javax.swing.JPanel();
        lbidusuarios = new javax.swing.JLabel();
        txtidusuarios = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        lblapellidos = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        lbidusuarios3 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblpassword = new javax.swing.JLabel();
        lblpassword2 = new javax.swing.JLabel();
        cbmperfil = new javax.swing.JComboBox<>();
        lblemail = new javax.swing.JLabel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();
        txtpassword2 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablausu = new javax.swing.JTable();
        lblbuscar = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        lbltotalregistros = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Usuarios");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("FrUsuarios"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Gestión de  Usuarios");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblperfil.setBackground(new java.awt.Color(153, 0, 0));
        lblperfil.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Registro de Usuarios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        lbidusuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbidusuarios.setForeground(new java.awt.Color(255, 255, 255));
        lbidusuarios.setText("Usuarios");

        txtidusuarios.setText(" ");
        txtidusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidusuariosActionPerformed(evt);
            }
        });

        lblnombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(255, 255, 255));
        lblnombre.setText("Nombre");

        txtnombre.setText(" ");
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        lblapellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblapellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblapellidos.setText("Apellidos");

        txtapellidos.setText(" ");
        txtapellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidosActionPerformed(evt);
            }
        });

        lbidusuarios3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbidusuarios3.setForeground(new java.awt.Color(255, 255, 255));
        lbidusuarios3.setText("Perfil");

        txtemail.setText(" ");
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        lblpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(255, 255, 255));
        lblpassword.setText("Password");

        lblpassword2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblpassword2.setForeground(new java.awt.Color(255, 255, 255));
        lblpassword2.setText("Confirmar ");

        cbmperfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Administrador", "Empleado" }));

        lblemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblemail.setForeground(new java.awt.Color(255, 255, 255));
        lblemail.setText("Email");

        btnnuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/Reservas.png"))); // NOI18N
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnguardar.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/save.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btncancelar.setBackground(new java.awt.Color(255, 255, 255));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/cancel.png"))); // NOI18N
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        txtpassword.setText("jPasswordField1");

        txtpassword2.setText("jPasswordField2");

        javax.swing.GroupLayout lblperfilLayout = new javax.swing.GroupLayout(lblperfil);
        lblperfil.setLayout(lblperfilLayout);
        lblperfilLayout.setHorizontalGroup(
            lblperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblperfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbmperfil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtpassword2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidusuarios, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtemail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lblperfilLayout.createSequentialGroup()
                        .addGroup(lblperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbidusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbidusuarios3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
            .addGroup(lblperfilLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        lblperfilLayout.setVerticalGroup(
            lblperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblperfilLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbidusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbidusuarios3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbmperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(lblperfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnuevo)
                    .addComponent(btnguardar)
                    .addComponent(btncancelar))
                .addGap(75, 75, 75))
        );

        btnnuevo.getAccessibleContext().setAccessibleName("Nuevo");
        btncancelar.getAccessibleContext().setAccessibleName("Cancelar");

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Usuarios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        tablausu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablausu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablausuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablausu);

        lblbuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblbuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblbuscar.setText("Buscar");

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/search.png"))); // NOI18N
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnborrar.setBackground(new java.awt.Color(255, 255, 255));
        btnborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/erase.png"))); // NOI18N
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        btnsalir.setBackground(new java.awt.Color(255, 255, 255));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/Home.png"))); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        lbltotalregistros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltotalregistros.setForeground(new java.awt.Color(255, 255, 255));
        lbltotalregistros.setText("Total Registros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblbuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbuscar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnbuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnborrar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnsalir, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnbuscar.getAccessibleContext().setAccessibleName("Buscar");
        btnborrar.getAccessibleContext().setAccessibleName("Borrar");
        lbltotalregistros.getAccessibleContext().setAccessibleName("Total Registros       ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblperfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(333, 333, 333))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        //Habilitamos los campos
        habilitar();  
        //Si el buton guardar contiene la etiqueta guardar 
        btnguardar.setText("Guardar");
        //Usamos la accion guardar
        acc="guardar";
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
    try{  
        //Validamos los campos
        //Valor seleccionado del combobox
        int selec = cbmperfil.getSelectedIndex();
        
        if (txtidusuarios.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un usuario", "Acceso a Usuarios", JOptionPane.ERROR_MESSAGE);
            txtidusuarios.requestFocus();
            return;
        }
        if (txtnombre.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un nombre", "Acceso a Usuarios", JOptionPane.ERROR_MESSAGE);
            txtnombre.requestFocus();
            return;
        }
        if (txtapellidos.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un apellidos", "Acceso a Usuarios", JOptionPane.ERROR_MESSAGE);
            txtapellidos.requestFocus();
            return;
        }
        if (txtemail.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un email", "Acceso a Usuarios", JOptionPane.ERROR_MESSAGE);
            txtemail.requestFocus();
            return;
        }
        if (txtpassword.getPassword().length == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar password", "Acceso a Usuarios", JOptionPane.ERROR_MESSAGE);
            txtpassword.requestFocus();
            return;
        }
        if (txtpassword2.getPassword().length == 0 ){
            JOptionPane.showConfirmDialog(rootPane, "Deben repetir el valor de password", "Acceso a Usuarios", JOptionPane.ERROR_MESSAGE);
            txtpassword2.requestFocus();
            return;
        }
        if (!Arrays.equals(txtpassword2.getPassword(), txtpassword.getPassword())){
            JOptionPane.showConfirmDialog(rootPane, "Deben ser iguales los valores de password", "Acceso a Usuarios", JOptionPane.ERROR_MESSAGE);
            txtpassword2.requestFocus();
            return;
        }            
        if (selec == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes seleccionar un perfil", "Acceso a Usuarios", JOptionPane.ERROR_MESSAGE);
            cbmperfil.requestFocus(); 
            return;
        }
        //Instanciamos ambas clases
        usu = new DatosUsuario();
        usuario = new Usuarios(); 
        //Recogo los datos de las cajas de texto
        usuario.setIdusuarios(txtidusuarios.getText());
        usuario.setNombre(txtnombre.getText());
        usuario.setApellidos(txtapellidos.getText());
        usuario.setEmail(txtemail.getText());
        usuario.setPassword(new String(txtpassword.getPassword()));
        usuario.setPassword(new String(txtpassword2.getPassword()));
        usuario.setPerfil(cbmperfil.getItemAt(selec));
        //Si la accion es guardar , ingreso el nuevo usuario y muestro el mensaje
        if (acc.equals("guardar")) {
            if (usu.nuevoUsuario(usuario)) {
               JOptionPane.showMessageDialog(rootPane, "Usuario ingresado correctamente");
               //Muestro los datos del nuevo usuario en la tabla
               MostrarDatosTabla("");
               //Inhabilito los campos
               inhabilitar();
            }
         //Si por el contrario la acción es editar. Tomamos el id del usuario
        }else if (acc.equals("editar")) {
           usuario.setIdusuarios(txtidusuarios.getText());
            //Modificamos el usuario y mostramos mensaje
            if (usu.modificarUsuario(usuario)) {
               JOptionPane.showMessageDialog(rootPane, "Usuario modificado correctamente");
               //Mostramos los datos modificados
               MostrarDatosTabla("");
               //Inhabilitamos datos
               inhabilitar();
            }
        } 
    }catch (HeadlessException e) {
             JOptionPane.showConfirmDialog(null,e);
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
      try{
        //Si el campo idusuarios es distinto de vacio, indicampos mensaje de seguridad al borrar
        if (!txtidusuarios.getText().equals("")) {
           int confirmar = JOptionPane.showConfirmDialog(rootPane, "Seguro que quiere eliminar el usuario","Confirmar",2);
            if (confirmar == 0) {
                usu = new DatosUsuario();
                usuario = new Usuarios();
                //Tomamos el idusuarios y borramos el usuario
                usuario.setIdusuarios(txtidusuarios.getText());
                usu.eliminarUsuario(usuario);
                MostrarDatosTabla(""); //Mostramos los cambios en la tabla
                inhabilitar();  //Inhabilitamos campos  
            }
        }
      }catch (HeadlessException e) {
             JOptionPane.showConfirmDialog(null,e);
        }
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
          //Al pulsar el boton buscar,capturamos la letra introducida y buscamos el usuario
          MostrarDatosTabla(txtbuscar.getText()); 
//        fillTable(txtbuscar.getText());
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtidusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidusuariosActionPerformed
        //Con el evento pasamos el foco a la siguiente caja de texto
        txtidusuarios.transferFocus();
    }//GEN-LAST:event_txtidusuariosActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        txtnombre.transferFocus();
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtapellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidosActionPerformed
        txtapellidos.transferFocus();
    }//GEN-LAST:event_txtapellidosActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        txtemail.transferFocus();
    }//GEN-LAST:event_txtemailActionPerformed

    private void tablausuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablausuMouseClicked
       //Cuando haga click en la fila de la tabla los datos pasan a sus cajas de texto 
       //El botón guardar cambia el texto a Editar y la acción pasa a ser editar
       btnguardar.setText("Editar");
       //El botón borrar se inhabilita
       btnborrar.setEnabled(true);
       //Habilitamos los campos
       habilitar();
       //La acción pasa a ser editar
       acc="editar";
       //Inhabilito el idusuarios al no poder modificarse por ser clave primaria
       txtidusuarios.setEnabled(false);
       //Capturamos la fila q ha sido cliqueada
       int fila= tablausu.rowAtPoint(evt.getPoint());
         //Tomamos los datos de la tabla y los pasamos a sus cajas de texto
        txtidusuarios.setText(tablausu.getValueAt(fila, 0).toString());
        txtnombre.setText(tablausu.getValueAt(fila, 1).toString());
        txtapellidos.setText(tablausu.getValueAt(fila, 2).toString());
        txtemail.setText(tablausu.getValueAt(fila, 3).toString());
        txtpassword.setText(tablausu.getValueAt(fila, 4).toString());
        txtpassword2.setText(tablausu.getValueAt(fila, 5).toString());
        cbmperfil.setSelectedItem(tablausu.getValueAt(fila, 6).toString());
 
    }//GEN-LAST:event_tablausuMouseClicked

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
         this.dispose(); //Salimos del sistema
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cbmperfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbidusuarios;
    private javax.swing.JLabel lbidusuarios3;
    private javax.swing.JLabel lblapellidos;
    private javax.swing.JLabel lblbuscar;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblpassword2;
    private javax.swing.JPanel lblperfil;
    private javax.swing.JLabel lbltotalregistros;
    private javax.swing.JTable tablausu;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtidusuarios;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JPasswordField txtpassword2;
    // End of variables declaration//GEN-END:variables

   
}
