
package Vistas;

import Clases.ImagenFondo;
import Clases.Usuarios;
import javax.swing.Box;

/**
 *
 * @author Ana
 */
public class FormInicio extends javax.swing.JFrame {
    /**
     * Creates new form FormInicio
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public FormInicio() {
        initComponents();
        //Título de ventana
        this.setTitle("Tradcbm");
        //Llamammos a la clase imagenfondo
        Principal.setBorder(new ImagenFondo());
        //Expandimos ancho y alto
        this.setExtendedState(FormInicio.MAXIMIZED_BOTH);
        lbperfil.setVisible(false);
        //Desplazamos el menu de bienvenida para que esté a la derecha
        menuBar.add(Box.createHorizontalGlue());
        menuBar.add(MenuLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JDesktopPane();
        lbperfil = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        MenuIcono = new javax.swing.JMenu();
        MenuAdministracion = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        MenuCompras = new javax.swing.JMenuItem();
        MenuInpuestos = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        MenuInformes = new javax.swing.JMenu();
        MenuRegistro = new javax.swing.JMenu();
        jMenuUsuarios = new javax.swing.JMenuItem();
        MenuAyuda = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenu();
        MenuLogin = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbperfil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbperfil.setForeground(new java.awt.Color(255, 255, 255));
        lbperfil.setText(" ");
        Principal.add(lbperfil);
        lbperfil.setBounds(190, 120, 370, 30);

        menuBar.setBackground(new java.awt.Color(0, 0, 0));
        menuBar.setForeground(new java.awt.Color(255, 255, 255));
        menuBar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        MenuIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/logotradcbm.png"))); // NOI18N
        MenuIcono.setText("TRADCBM");
        menuBar.add(MenuIcono);

        MenuAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/admi.png"))); // NOI18N
        MenuAdministracion.setMnemonic('f');
        MenuAdministracion.setText("Administracion");

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/clientes.png"))); // NOI18N
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Clientes");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        MenuAdministracion.add(openMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/proyectos2.png"))); // NOI18N
        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Proyectos");
        MenuAdministracion.add(saveMenuItem);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/factura-roja2.png"))); // NOI18N
        jMenuItem1.setText("Facturas");
        MenuAdministracion.add(jMenuItem1);

        saveAsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        saveAsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/proveedores.png"))); // NOI18N
        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Proveedores");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        MenuAdministracion.add(saveAsMenuItem);

        MenuCompras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        MenuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/compras2.png"))); // NOI18N
        MenuCompras.setMnemonic('x');
        MenuCompras.setText("Compras");
        MenuCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuComprasActionPerformed(evt);
            }
        });
        MenuAdministracion.add(MenuCompras);

        menuBar.add(MenuAdministracion);

        MenuInpuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/impuestos.png"))); // NOI18N
        MenuInpuestos.setMnemonic('e');
        MenuInpuestos.setText("Impuestos ");

        cutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        cutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/irpf.png"))); // NOI18N
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("IRPF");
        MenuInpuestos.add(cutMenuItem);

        copyMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        copyMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/iva.png"))); // NOI18N
        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("IVA");
        MenuInpuestos.add(copyMenuItem);

        menuBar.add(MenuInpuestos);

        MenuInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/informe.png"))); // NOI18N
        MenuInformes.setText("Informes");
        menuBar.add(MenuInformes);

        MenuRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/trabajadores.png"))); // NOI18N
        MenuRegistro.setText("Registro");

        jMenuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/user.png"))); // NOI18N
        jMenuUsuarios.setText("Usuarios");
        jMenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuariosActionPerformed(evt);
            }
        });
        MenuRegistro.add(jMenuUsuarios);

        menuBar.add(MenuRegistro);

        MenuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/ayuda.JPG"))); // NOI18N
        MenuAyuda.setMnemonic('h');
        MenuAyuda.setText("Ayuda");

        contentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/about.png"))); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Acerca de..");
        MenuAyuda.add(contentMenuItem);

        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/ayuda.JPG"))); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Ayuda");
        MenuAyuda.add(aboutMenuItem);

        menuBar.add(MenuAyuda);

        MenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/salir1.png"))); // NOI18N
        MenuSalir.setText("Salir");
        MenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSalirMouseClicked(evt);
            }
        });
        menuBar.add(MenuSalir);

        MenuLogin.setText(" ");
        MenuLogin.setToolTipText("");
        MenuLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        menuBar.add(MenuLogin);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 1600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuComprasActionPerformed
            //Instancia del formulario usuarios
            FormCompras formComp = new FormCompras();
            Principal.add(formComp); //Añado el formulario al desktop
            formComp.toFront(); //Lo traigo al frente
            formComp.setVisible(true);    }//GEN-LAST:event_MenuComprasActionPerformed

    private void jMenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuariosActionPerformed
        //Instancia del formulario usuarios
        FormUsuarios formusu = new FormUsuarios();
        Principal.add(formusu); //Añado el formulario al desktop
        formusu.toFront(); //Lo traigo al frente
        formusu.setVisible(true);

    }//GEN-LAST:event_jMenuUsuariosActionPerformed

    private void MenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSalirMouseClicked
        // Salir del sistema
        System.exit(0);
    }//GEN-LAST:event_MenuSalirMouseClicked

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu MenuAdministracion;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenuItem MenuCompras;
    private javax.swing.JMenu MenuIcono;
    private javax.swing.JMenu MenuInformes;
    private javax.swing.JMenu MenuInpuestos;
    public static javax.swing.JMenu MenuLogin;
    public static javax.swing.JMenu MenuRegistro;
    private javax.swing.JMenu MenuSalir;
    private javax.swing.JDesktopPane Principal;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuUsuarios;
    public static javax.swing.JLabel lbperfil;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

    void setPerfil(Usuarios usuario) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    Object getPefil(Usuarios usuario) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
